# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ListService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ListService.proto\x12\x0clist_service\"\x0e\n\x0c\x45mptyMessage\"\x14\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x18\n\x08ListData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x05\"\x16\n\x05\x43ount\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"\x16\n\x05Index\x12\r\n\x05index\x18\x01 \x01(\r\")\n\nInsertData\x12\r\n\x05index\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\x32\xec\x05\n\x0bListService\x12@\n\x08ShowList\x12\x1a.list_service.EmptyMessage\x1a\x16.list_service.ListData\"\x00\x12\x36\n\x06\x41ppend\x12\x12.list_service.Data\x1a\x16.list_service.ListData\"\x00\x12=\n\x05\x43lear\x12\x1a.list_service.EmptyMessage\x1a\x16.list_service.ListData\"\x00\x12<\n\x04\x43opy\x12\x1a.list_service.EmptyMessage\x1a\x16.list_service.ListData\"\x00\x12\x42\n\rCountElements\x12\x1a.list_service.EmptyMessage\x1a\x13.list_service.Count\"\x00\x12:\n\x06\x45xtend\x12\x16.list_service.ListData\x1a\x16.list_service.ListData\"\x00\x12;\n\x0eIndexOfElement\x12\x12.list_service.Data\x1a\x13.list_service.Index\"\x00\x12<\n\x06Insert\x12\x18.list_service.InsertData\x1a\x16.list_service.ListData\"\x00\x12\x34\n\x03Pop\x12\x13.list_service.Index\x1a\x16.list_service.ListData\"\x00\x12\x36\n\x06Remove\x12\x12.list_service.Data\x1a\x16.list_service.ListData\"\x00\x12?\n\x07Reverse\x12\x1a.list_service.EmptyMessage\x1a\x16.list_service.ListData\"\x00\x12<\n\x04Sort\x12\x1a.list_service.EmptyMessage\x1a\x16.list_service.ListData\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ListService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=35
  _EMPTYMESSAGE._serialized_end=49
  _DATA._serialized_start=51
  _DATA._serialized_end=71
  _LISTDATA._serialized_start=73
  _LISTDATA._serialized_end=97
  _COUNT._serialized_start=99
  _COUNT._serialized_end=121
  _INDEX._serialized_start=123
  _INDEX._serialized_end=145
  _INSERTDATA._serialized_start=147
  _INSERTDATA._serialized_end=188
  _LISTSERVICE._serialized_start=191
  _LISTSERVICE._serialized_end=939
# @@protoc_insertion_point(module_scope)
